# Generated by Django 6.0.5 on 2026-06-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_notification_product_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
