# Generated by Django 6.0.5 on 2026-06-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_notification_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('low_stock', 'Low Stock'), ('restock', 'Restock'), ('system', 'System')], default='general', max_length=20),
        ),
    ]
