# Generated by Django 6.0.5 on 2026-06-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_notification_action_url_alter_notification_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
